spring.application.name=vnpay-demo

# VNPay Configuration
vnpay.payUrl=${VNPAY_PAY_URL}
vnpay.returnUrl=${VNPAY_RETURN_URL}
vnpay.tmnCode=${VNPAY_TMN_CODE}
vnpay.hashSecret=${VNPAY_HASH_SECRET}
vnpay.apiUrl=${VNPAY_API_URL}

